from .livros import Livros
from .acao import Acao
from .vantagens import Vantagens
from .desvantagens import Desvantagens
from .alcances_magia import AlcancesMagia
from .duracoes_magia import DuracoesMagia
from .escolas_magia import EscolasMagia
from .magias import Magias
from .especializacoes import Especializacoes
from .pericias import Pericias
from .bonus_caracteristicas import BonusCaracteristicas
from .vantagens_unicas import VantagensUnicas
from .fichas import Fichas