# Generated by Django 2.2.3 on 2019-08-25 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vantagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('cost', models.IntegerField(verbose_name='Custo')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Vantagem',
                'verbose_name_plural': 'Vantagens',
            },
        ),
    ]
