# Generated by Django 2.2.5 on 2019-09-06 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('bonus', models.IntegerField(verbose_name='Bonus')),
                ('attribute', models.CharField(choices=[('FO', 'Força'), ('HA', 'Habilidade'), ('RE', 'Resistencia'), ('AR', 'Armadura'), ('PO', 'Poder de Fogo'), ('PV', 'Poder de Vida'), ('PM', 'Poder de Magia')], max_length=2, verbose_name='Atributo')),
                ('kind', models.CharField(choices=[('S', 'Selecionar'), ('A', 'Ativo')], max_length=2, verbose_name='Tipo')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Caracteristica',
                'verbose_name_plural': 'Caracteristicas',
            },
        ),
        migrations.CreateModel(
            name='AlcancesMagia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Alcance da Magia',
                'verbose_name_plural': 'Alcances de Magia',
            },
        ),
        migrations.CreateModel(
            name='BonusCaracteristicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('actions', models.ManyToManyField(to='tresDeT.Acao', verbose_name='Ação')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Caracteristica',
                'verbose_name_plural': 'Caracteristicas',
            },
        ),
        migrations.CreateModel(
            name='Desvantagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('cost', models.IntegerField(verbose_name='Custo')),
                ('page', models.IntegerField(verbose_name='Pagina')),
                ('magic_points', models.IntegerField(null=True, verbose_name='Pontos de Magia')),
                ('use_magic_points', models.BooleanField(default=False, verbose_name='Usa Pontos de Magia')),
                ('actions', models.ManyToManyField(to='tresDeT.Acao', verbose_name='Ação')),
            ],
            options={
                'verbose_name': 'Desvantagem',
                'verbose_name_plural': 'desvantagens',
            },
        ),
        migrations.CreateModel(
            name='DuracoesMagia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Duração da Magia',
                'verbose_name_plural': 'Durações da Magia',
            },
        ),
        migrations.CreateModel(
            name='EscolasMagia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Escola da Magia',
                'verbose_name_plural': 'Escolas da Magia',
            },
        ),
        migrations.CreateModel(
            name='Especializacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('actions', models.ManyToManyField(to='tresDeT.Acao', verbose_name='Ação')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Especialização',
                'verbose_name_plural': 'Especializações',
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Pericias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('cost', models.IntegerField(verbose_name='Custo')),
                ('page', models.IntegerField(verbose_name='Pagina')),
                ('actions', models.ManyToManyField(to='tresDeT.Acao', verbose_name='Ação')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresDeT.Livros', verbose_name='Livro')),
                ('specializations', models.ManyToManyField(to='tresDeT.Especializacoes', verbose_name='Especializações')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Pericia',
                'verbose_name_plural': 'Pericias',
            },
        ),
        migrations.CreateModel(
            name='Vantagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('cost', models.IntegerField(verbose_name='Custo')),
                ('page', models.IntegerField(verbose_name='Pagina')),
                ('magic_points', models.IntegerField(null=True, verbose_name='Pontos de Magia')),
                ('use_magic_points', models.BooleanField(default=False, verbose_name='Usa Pontos de Magia')),
                ('actions', models.ManyToManyField(to='tresDeT.Acao', verbose_name='Ação')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresDeT.Livros', verbose_name='Livro')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Vantagem',
                'verbose_name_plural': 'Vantagens',
            },
        ),
        migrations.CreateModel(
            name='VantagensUnicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('cost', models.CharField(max_length=50, verbose_name='Custo')),
                ('page', models.IntegerField(verbose_name='Pagina')),
                ('bonus', models.ManyToManyField(blank=True, to='tresDeT.BonusCaracteristicas', verbose_name='Bonus')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresDeT.Livros', verbose_name='Livro')),
                ('desvantagens', models.ManyToManyField(blank=True, to='tresDeT.Desvantagens', verbose_name='Desvantages')),
                ('especializacoes', models.ManyToManyField(blank=True, to='tresDeT.Especializacoes', verbose_name='Especializacões')),
                ('pericias', models.ManyToManyField(blank=True, to='tresDeT.Pericias', verbose_name='Pericias')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema')),
                ('vantagens', models.ManyToManyField(blank=True, to='tresDeT.Vantagens', verbose_name='Vantagens')),
            ],
            options={
                'verbose_name': 'Vantagem Unica',
                'verbose_name_plural': 'Vantagens Unicas',
            },
        ),
        migrations.CreateModel(
            name='Magias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('cost', models.CharField(max_length=50, verbose_name='Custo')),
                ('page', models.IntegerField(verbose_name='Pagina')),
                ('magic_points', models.IntegerField(null=True, verbose_name='Pontos de Magia')),
                ('actions', models.ManyToManyField(to='tresDeT.Acao', verbose_name='Ação')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresDeT.Livros', verbose_name='Livro')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresDeT.DuracoesMagia', verbose_name='Duração')),
                ('reach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresDeT.AlcancesMagia', verbose_name='Alcance')),
                ('requirements_desvantagens', models.ManyToManyField(blank=True, to='tresDeT.Desvantagens', verbose_name='Exigencia Desvantagem')),
                ('requirements_vantagens', models.ManyToManyField(blank=True, to='tresDeT.Vantagens', verbose_name='Exigencia Vantagem')),
                ('school', models.ManyToManyField(to='tresDeT.EscolasMagia', verbose_name='Escola')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Magia',
                'verbose_name_plural': 'Magias',
            },
        ),
        migrations.CreateModel(
            name='Fichas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('points', models.IntegerField(verbose_name='Pontos')),
                ('force', models.IntegerField(verbose_name='Força')),
                ('abiliity', models.IntegerField(verbose_name='Habilidade')),
                ('resistance', models.IntegerField(verbose_name='Resistencia')),
                ('armor', models.IntegerField(verbose_name='Armadura')),
                ('fire_power', models.IntegerField(verbose_name='Poder de Fogo')),
                ('health_points', models.IntegerField(verbose_name='Pontos de vida')),
                ('magic_points', models.IntegerField(verbose_name='Pontos de magia')),
                ('experience_points', models.IntegerField(verbose_name='Pontos de Experiencia')),
                ('damage_types', models.CharField(blank=True, max_length=250, verbose_name='Tipos de dano')),
                ('items', models.CharField(blank=True, max_length=250, verbose_name='Itens')),
                ('story', models.CharField(blank=True, max_length=250, verbose_name='Historia')),
                ('benefits', models.ManyToManyField(blank=True, to='tresDeT.Vantagens', verbose_name='Vantagens')),
                ('disadvantages', models.ManyToManyField(blank=True, to='tresDeT.Desvantagens', verbose_name='Desvantagens')),
                ('expertise', models.ManyToManyField(blank=True, to='tresDeT.Pericias', verbose_name='Pericias')),
                ('magic', models.ManyToManyField(blank=True, to='tresDeT.Magias', verbose_name='Magias')),
                ('specializations', models.ManyToManyField(blank=True, to='tresDeT.Especializacoes', verbose_name='Especializações')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema')),
                ('unique_benefits', models.ManyToManyField(blank=True, to='tresDeT.VantagensUnicas', verbose_name='Vantagens Unicas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ficha 3D&T',
                'verbose_name_plural': 'Fichas 3D&T',
            },
        ),
        migrations.AddField(
            model_name='desvantagens',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresDeT.Livros', verbose_name='Livro'),
        ),
        migrations.AddField(
            model_name='desvantagens',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema'),
        ),
    ]
