# Generated by Django 2.2.3 on 2019-08-28 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('tresDeT', '0002_desvantagens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('cost', models.CharField(max_length=30, verbose_name='Custo')),
                ('duration', models.CharField(max_length=30, verbose_name='Duração')),
                ('reach', models.CharField(max_length=30, verbose_name='Alcance')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Magia',
                'verbose_name_plural': 'Magias',
            },
        ),
    ]
