# Generated by Django 2.2.3 on 2019-08-29 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tresDeT', '0003_magias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magias',
            name='cost',
            field=models.CharField(max_length=50, verbose_name='Custo'),
        ),
        migrations.AlterField(
            model_name='magias',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='magias',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='magias',
            name='reach',
            field=models.CharField(max_length=50, verbose_name='Alcance'),
        ),
        migrations.CreateModel(
            name='Fichas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('points', models.IntegerField(verbose_name='Pontos')),
                ('force', models.IntegerField(verbose_name='Força')),
                ('abiliity', models.IntegerField(verbose_name='Habilidade')),
                ('resistance', models.IntegerField(verbose_name='Resistencia')),
                ('armor', models.IntegerField(verbose_name='Armadura')),
                ('fire_power', models.IntegerField(verbose_name='Poder de Fogo')),
                ('health_points', models.IntegerField(verbose_name='Pontos de vida')),
                ('magic_points', models.IntegerField(verbose_name='Pontos de magia')),
                ('experience_points', models.IntegerField(verbose_name='Pontos de Experiencia')),
                ('damage_types', models.CharField(max_length=250, verbose_name='Tipos de dano')),
                ('items', models.CharField(max_length=250, verbose_name='Itens')),
                ('story', models.CharField(max_length=250, verbose_name='Historia')),
                ('benefits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresDeT.Vantagens', verbose_name='Vantagens')),
                ('disadvantages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresDeT.Desvantagens', verbose_name='Desvantagens')),
                ('magic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresDeT.Magias', verbose_name='Magias')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RPGSystem', verbose_name='Sistema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ficha 3D&T',
                'verbose_name_plural': 'Fichas 3D&T',
            },
        ),
    ]
