# Generated by Django 2.2.3 on 2019-08-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tresDeT', '0004_auto_20190829_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='benefits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tresDeT.Vantagens', verbose_name='Vantagens'),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='disadvantages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tresDeT.Desvantagens', verbose_name='Desvantagens'),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='magic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tresDeT.Magias', verbose_name='Magias'),
        ),
    ]
