# Generated by Django 2.2.3 on 2019-08-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresDeT', '0005_auto_20190829_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichas',
            name='benefits',
        ),
        migrations.AddField(
            model_name='fichas',
            name='benefits',
            field=models.ManyToManyField(null=True, to='tresDeT.Vantagens', verbose_name='Vantagens'),
        ),
        migrations.RemoveField(
            model_name='fichas',
            name='disadvantages',
        ),
        migrations.AddField(
            model_name='fichas',
            name='disadvantages',
            field=models.ManyToManyField(null=True, to='tresDeT.Desvantagens', verbose_name='Desvantagens'),
        ),
        migrations.RemoveField(
            model_name='fichas',
            name='magic',
        ),
        migrations.AddField(
            model_name='fichas',
            name='magic',
            field=models.ManyToManyField(null=True, to='tresDeT.Magias', verbose_name='Magias'),
        ),
    ]
