# Generated by Django 2.2.5 on 2019-09-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresDeT', '0006_auto_20190829_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='magias',
            name='school',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Escola'),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='benefits',
            field=models.ManyToManyField(to='tresDeT.Vantagens', verbose_name='Vantagens'),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='disadvantages',
            field=models.ManyToManyField(to='tresDeT.Desvantagens', verbose_name='Desvantagens'),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='magic',
            field=models.ManyToManyField(to='tresDeT.Magias', verbose_name='Magias'),
        ),
    ]
