# Generated by Django 2.2.3 on 2019-08-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RPGSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('site', models.CharField(max_length=100, verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Sistema de RPG',
                'verbose_name_plural': 'Sistemas de RPG',
            },
        ),
    ]
