from .vantagens_model_test_case import VantagensModelTestCase
from .desvantagens_model_test_case import DesvantagensModelTestCase
from .magias_model_test_case import MagiasModelTestCase
from .fichas_model_test_case import FichasModelTestCase
from .livros_model_test_case import LivrosModelTestCase