from .user_view_test_case import UserViewTestCase
from .rpg_system_view_test_case import RPGSystemViewTestCase
from .vantagens_view_test_case import VantagensViewTestCase
from .desvantagens_view_test_case import DesvantagensViewTestCase